name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Build Release Library
      run: ./gradlew :library:assembleRelease

    - name: Generate Sources and Javadoc
      run: ./gradlew :library:sourceReleaseJar :library:javadocReleaseJar

    - name: Verify Maven Publication
      run: ./gradlew :library:publishToMavenLocal

    - name: Run Tests
      run: ./gradlew test

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
